"""add review fields to servitutter

Revision ID: acc4f85bdef2
Revises: 59d5f1aee10b
Create Date: 2026-03-23 19:51:05.372067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acc4f85bdef2'
down_revision: Union[str, Sequence[str], None] = '59d5f1aee10b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servitutter', sa.Column('review_status', sa.String(), nullable=True))
    op.add_column('servitutter', sa.Column('review_remarks', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('servitutter', 'review_remarks')
    op.drop_column('servitutter', 'review_status')
    # ### end Alembic commands ###
